#include <GL/glut.h>

#include "scene.h"
#include "carrom.h"
#include "physics.h"
#include "drawable.h"
#include "utilities.h"

void drawBoardFrame(void) {
	glColor3f(BOARD_EDGE_COLOR);
	glBegin(GL_POLYGON);
		glVertex2f(-BOARD_SCALING_FACTOR * (1 + BOARD_EDGE_WIDTH), BOARD_SCALING_FACTOR * (1 + BOARD_EDGE_WIDTH));
		glVertex2f(-BOARD_SCALING_FACTOR * (1 + BOARD_EDGE_WIDTH), -BOARD_SCALING_FACTOR * (1 + BOARD_EDGE_WIDTH));
		glVertex2f(-BOARD_SCALING_FACTOR, -BOARD_SCALING_FACTOR * (1 + BOARD_EDGE_WIDTH));
		glVertex2f(-BOARD_SCALING_FACTOR, BOARD_SCALING_FACTOR * (1 + BOARD_EDGE_WIDTH));
	glEnd();

	glBegin(GL_POLYGON);
		glVertex2f(BOARD_SCALING_FACTOR * (1 + BOARD_EDGE_WIDTH), BOARD_SCALING_FACTOR * (1 + BOARD_EDGE_WIDTH));
		glVertex2f(BOARD_SCALING_FACTOR * (1 + BOARD_EDGE_WIDTH), -BOARD_SCALING_FACTOR * (1 + BOARD_EDGE_WIDTH));
		glVertex2f(BOARD_SCALING_FACTOR, -BOARD_SCALING_FACTOR * (1 + BOARD_EDGE_WIDTH));
		glVertex2f(BOARD_SCALING_FACTOR, BOARD_SCALING_FACTOR * (1 + BOARD_EDGE_WIDTH));
	glEnd();

	glBegin(GL_POLYGON);
		glVertex2f(-BOARD_SCALING_FACTOR * (1 + BOARD_EDGE_WIDTH), BOARD_SCALING_FACTOR * (1 + BOARD_EDGE_WIDTH));
		glVertex2f(BOARD_SCALING_FACTOR * (1 + BOARD_EDGE_WIDTH), BOARD_SCALING_FACTOR * (1 + BOARD_EDGE_WIDTH));
		glVertex2f(BOARD_SCALING_FACTOR * (1 + BOARD_EDGE_WIDTH), BOARD_SCALING_FACTOR);
		glVertex2f(-BOARD_SCALING_FACTOR * (1 + BOARD_EDGE_WIDTH), BOARD_SCALING_FACTOR);
	glEnd();

	glBegin(GL_POLYGON);
		glVertex2f(-BOARD_SCALING_FACTOR * (1 + BOARD_EDGE_WIDTH), -BOARD_SCALING_FACTOR * (1 + BOARD_EDGE_WIDTH));
		glVertex2f(BOARD_SCALING_FACTOR * (1 + BOARD_EDGE_WIDTH), -BOARD_SCALING_FACTOR * (1 + BOARD_EDGE_WIDTH));
		glVertex2f(BOARD_SCALING_FACTOR * (1 + BOARD_EDGE_WIDTH), -BOARD_SCALING_FACTOR);
		glVertex2f(-BOARD_SCALING_FACTOR * (1 + BOARD_EDGE_WIDTH), -BOARD_SCALING_FACTOR);
	glEnd();
}


void drawBoardBackground(void) {
	glColor3f(BOARD_COLOR);
	glBegin(GL_POLYGON);
		glEdgeFlag(GL_TRUE);
		glVertex2f(-BOARD_SCALING_FACTOR, BOARD_SCALING_FACTOR);
		glVertex2f(BOARD_SCALING_FACTOR, BOARD_SCALING_FACTOR);
		glVertex2f(BOARD_SCALING_FACTOR, -BOARD_SCALING_FACTOR);
		glVertex2f(-BOARD_SCALING_FACTOR, -BOARD_SCALING_FACTOR);
		glEdgeFlag(GL_FALSE);
	glEnd();
}

void drawBoardBaseLines(void) {
	glColor3f(BOARD_LINE_COLOR);
	// top base line
	glBegin(GL_LINES);
		glVertex2f(-(BOARD_SCALING_FACTOR * (1 - BOARD_LINES_LENGTH - BOARD_LINES_WIDTH - BASE_LINE_SIZE)), (BOARD_SCALING_FACTOR * (1 - BOARD_LINES_LENGTH)));
		glVertex2f((BOARD_SCALING_FACTOR * (1 - BOARD_LINES_LENGTH - BOARD_LINES_WIDTH - BASE_LINE_SIZE)), (BOARD_SCALING_FACTOR * (1 - BOARD_LINES_LENGTH)));
		glVertex2f(-(BOARD_SCALING_FACTOR * (1 - BOARD_LINES_LENGTH - BOARD_LINES_WIDTH - BASE_LINE_SIZE)), (BOARD_SCALING_FACTOR * (1 - BOARD_LINES_LENGTH - BOARD_LINES_WIDTH)));
		glVertex2f((BOARD_SCALING_FACTOR * (1 - BOARD_LINES_LENGTH - BOARD_LINES_WIDTH - BASE_LINE_SIZE)), (BOARD_SCALING_FACTOR * (1 - BOARD_LINES_LENGTH - BOARD_LINES_WIDTH)));
	glEnd();
	// bottom base line
	glBegin(GL_LINES);
		glVertex2f(-(BOARD_SCALING_FACTOR * (1 - BOARD_LINES_LENGTH - BOARD_LINES_WIDTH - BASE_LINE_SIZE)), -(BOARD_SCALING_FACTOR * (1 - BOARD_LINES_LENGTH)));
		glVertex2f((BOARD_SCALING_FACTOR * (1 - BOARD_LINES_LENGTH - BOARD_LINES_WIDTH - BASE_LINE_SIZE)), -(BOARD_SCALING_FACTOR * (1 - BOARD_LINES_LENGTH)));
		glVertex2f(-(BOARD_SCALING_FACTOR * (1 - BOARD_LINES_LENGTH - BOARD_LINES_WIDTH - BASE_LINE_SIZE)), -(BOARD_SCALING_FACTOR * (1 - BOARD_LINES_LENGTH - BOARD_LINES_WIDTH)));
		glVertex2f((BOARD_SCALING_FACTOR * (1 - BOARD_LINES_LENGTH - BOARD_LINES_WIDTH - BASE_LINE_SIZE)), -(BOARD_SCALING_FACTOR * (1 - BOARD_LINES_LENGTH - BOARD_LINES_WIDTH)));
	glEnd();
	// left base line
	glBegin(GL_LINES);
		glVertex2f(-(BOARD_SCALING_FACTOR * (1 - BOARD_LINES_LENGTH)), -(BOARD_SCALING_FACTOR * (1 - BOARD_LINES_LENGTH - BOARD_LINES_WIDTH - BASE_LINE_SIZE)));
		glVertex2f(-(BOARD_SCALING_FACTOR * (1 - BOARD_LINES_LENGTH)), (BOARD_SCALING_FACTOR * (1 - BOARD_LINES_LENGTH - BOARD_LINES_WIDTH - BASE_LINE_SIZE)));
		glVertex2f(-(BOARD_SCALING_FACTOR * (1 - BOARD_LINES_LENGTH - BOARD_LINES_WIDTH)), -(BOARD_SCALING_FACTOR * (1 - BOARD_LINES_LENGTH - BOARD_LINES_WIDTH - BASE_LINE_SIZE)));
		glVertex2f(-(BOARD_SCALING_FACTOR * (1 - BOARD_LINES_LENGTH - BOARD_LINES_WIDTH)), (BOARD_SCALING_FACTOR * (1 - BOARD_LINES_LENGTH - BOARD_LINES_WIDTH - BASE_LINE_SIZE)));
	glEnd();
	// right base line
	glBegin(GL_LINES);
		glVertex2f((BOARD_SCALING_FACTOR * (1 - BOARD_LINES_LENGTH)), -(BOARD_SCALING_FACTOR * (1 - BOARD_LINES_LENGTH - BOARD_LINES_WIDTH - BASE_LINE_SIZE)));
		glVertex2f((BOARD_SCALING_FACTOR * (1 - BOARD_LINES_LENGTH)), (BOARD_SCALING_FACTOR * (1 - BOARD_LINES_LENGTH - BOARD_LINES_WIDTH - BASE_LINE_SIZE)));
		glVertex2f((BOARD_SCALING_FACTOR * (1 - BOARD_LINES_LENGTH - BOARD_LINES_WIDTH)), -(BOARD_SCALING_FACTOR * (1 - BOARD_LINES_LENGTH - BOARD_LINES_WIDTH - BASE_LINE_SIZE)));
		glVertex2f((BOARD_SCALING_FACTOR * (1 - BOARD_LINES_LENGTH - BOARD_LINES_WIDTH)), (BOARD_SCALING_FACTOR * (1 - BOARD_LINES_LENGTH - BOARD_LINES_WIDTH - BASE_LINE_SIZE)));
	glEnd();
}

void drawBoardCircles(void) {
	glColor3f(BOARD_LINE_COLOR);
	// display the center circle
	drawCircleOutline(BOARD_CIRCLE_RADIUS, 0.0, 0.0, CDA, -3, CDA);
	// outline the circles at both ends of the base line
	// left and bottom base lines
	drawCircleOutline((BOARD_LINES_WIDTH / 2.00), -(1 - BOARD_LINES_LENGTH - BOARD_LINES_WIDTH - BASE_LINE_SIZE), (1 - BOARD_LINES_LENGTH - (BOARD_LINES_WIDTH / 2.0)), CDA, -3, CDA);
	drawCircleOutline((BOARD_LINES_WIDTH / 2.00), (1 - BOARD_LINES_LENGTH - BOARD_LINES_WIDTH - BASE_LINE_SIZE), (1 - BOARD_LINES_LENGTH - (BOARD_LINES_WIDTH / 2.0)), CDA, -3, CDA);
	drawCircleOutline((BOARD_LINES_WIDTH / 2.00), (1 - BOARD_LINES_LENGTH - (BOARD_LINES_WIDTH / 2.0)), (1 - BOARD_LINES_LENGTH - BOARD_LINES_WIDTH - BASE_LINE_SIZE), CDA, -3, CDA);
	drawCircleOutline((BOARD_LINES_WIDTH / 2.00), (1 - BOARD_LINES_LENGTH - (BOARD_LINES_WIDTH / 2.0)), -(1 - BOARD_LINES_LENGTH - BOARD_LINES_WIDTH - BASE_LINE_SIZE), CDA, -3, CDA);
	// right and top base lines
	drawCircleOutline((BOARD_LINES_WIDTH / 2.00), -(1 - BOARD_LINES_LENGTH - BOARD_LINES_WIDTH - BASE_LINE_SIZE), -(1 - BOARD_LINES_LENGTH -(BOARD_LINES_WIDTH / 2.0)), CDA, -3, CDA);
	drawCircleOutline((BOARD_LINES_WIDTH / 2.00), (1 - BOARD_LINES_LENGTH - BOARD_LINES_WIDTH - BASE_LINE_SIZE), -(1 - BOARD_LINES_LENGTH -(BOARD_LINES_WIDTH / 2.0)), CDA, -3, CDA);
	drawCircleOutline((BOARD_LINES_WIDTH / 2.00), -(1 - BOARD_LINES_LENGTH - (BOARD_LINES_WIDTH / 2.0)), (1 - BOARD_LINES_LENGTH - BOARD_LINES_WIDTH - BASE_LINE_SIZE), CDA, -3, CDA);
	drawCircleOutline((BOARD_LINES_WIDTH / 2.00), -(1 - BOARD_LINES_LENGTH - (BOARD_LINES_WIDTH / 2.0)), -(1 - BOARD_LINES_LENGTH - BOARD_LINES_WIDTH - BASE_LINE_SIZE), CDA, -3, CDA);
	// fill the outlined circles with appropriate color
	// left and bottom base lines
	glColor3f(EDGE_DOT_COLOR);
	drawCircleFilled(EDGE_DOT_RADIUS, -(1 - BOARD_LINES_LENGTH - BOARD_LINES_WIDTH - BASE_LINE_SIZE), -(1 - BOARD_LINES_LENGTH - (BOARD_LINES_WIDTH /2.0)), CDA);
	drawCircleFilled(EDGE_DOT_RADIUS, (1 - BOARD_LINES_LENGTH - BOARD_LINES_WIDTH - BASE_LINE_SIZE), -(1 - BOARD_LINES_LENGTH - (BOARD_LINES_WIDTH / 2.0)), CDA);
	drawCircleFilled(EDGE_DOT_RADIUS, -(1 - BOARD_LINES_LENGTH - (BOARD_LINES_WIDTH / 2.0)), (1 - BOARD_LINES_LENGTH - BOARD_LINES_WIDTH - BASE_LINE_SIZE), CDA);
	drawCircleFilled(EDGE_DOT_RADIUS, -(1 - BOARD_LINES_LENGTH - (BOARD_LINES_WIDTH / 2.0)), -(1 - BOARD_LINES_LENGTH - BOARD_LINES_WIDTH - BASE_LINE_SIZE), CDA);
	// right and top base lines
 	drawCircleFilled(EDGE_DOT_RADIUS, -(1 - BOARD_LINES_LENGTH - BOARD_LINES_WIDTH - BASE_LINE_SIZE), (1 - BOARD_LINES_LENGTH - (BOARD_LINES_WIDTH / 2.0)), CDA);
	drawCircleFilled(EDGE_DOT_RADIUS, (1 - BOARD_LINES_LENGTH - BOARD_LINES_WIDTH - BASE_LINE_SIZE), (1 - BOARD_LINES_LENGTH - (BOARD_LINES_WIDTH / 2.0)), CDA);
	drawCircleFilled(EDGE_DOT_RADIUS, (1 - BOARD_LINES_LENGTH - (BOARD_LINES_WIDTH / 2.0)), (1 - BOARD_LINES_LENGTH - BOARD_LINES_WIDTH - BASE_LINE_SIZE), CDA);
	drawCircleFilled(EDGE_DOT_RADIUS, (1 - BOARD_LINES_LENGTH - (BOARD_LINES_WIDTH / 2.0)), -(1 - BOARD_LINES_LENGTH - BOARD_LINES_WIDTH - BASE_LINE_SIZE), CDA);
	// draw and fill the pot with appropriate color
	glColor3f(POT_COLOR);
	drawCircleFilled(POT_CIRCLE_RADIUS, -(1 - POT_CIRCLE_RADIUS), (1 - POT_CIRCLE_RADIUS), CDA);
	drawCircleFilled(POT_CIRCLE_RADIUS, (1 - POT_CIRCLE_RADIUS), (1 - POT_CIRCLE_RADIUS), CDA);
	drawCircleFilled(POT_CIRCLE_RADIUS, (1 - POT_CIRCLE_RADIUS), -(1 - POT_CIRCLE_RADIUS), CDA);
	drawCircleFilled(POT_CIRCLE_RADIUS, -(1 - POT_CIRCLE_RADIUS), -(1 - POT_CIRCLE_RADIUS), CDA);
}

void drawBoardArrows(short position) {
	float radius = BOARD_CIRCLE_RADIUS / 2.0;
	float centerX = BOARD_SCALING_FACTOR * (ARROW_HEAD_POINT + (BOARD_CIRCLE_RADIUS / (2.0 * ROOT_TWO)));
	float centerY = centerX;
	glColor3f(BOARD_LINE_COLOR);

	switch(position) {
		case TOP_LEFT:
			centerX *= -1;
			glBegin(GL_LINES);
				glVertex2f(-BOARD_SCALING_FACTOR * ARROW_HEAD_POINT, BOARD_SCALING_FACTOR * ARROW_HEAD_POINT);
				glVertex2f(-BOARD_SCALING_FACTOR * ARROW_BASE_POINT, BOARD_SCALING_FACTOR * ARROW_BASE_POINT);
			glEnd();

			glBegin(GL_TRIANGLES);
				glVertex2f(-(BOARD_SCALING_FACTOR * ARROW_BASE_POINT + ARROW_HEAD_SIZE / 4 * ROOT_TWO) * 0.99, (BOARD_SCALING_FACTOR * ARROW_BASE_POINT - ARROW_HEAD_SIZE / 4 * ROOT_TWO) * 0.99);
				glVertex2f(-(BOARD_SCALING_FACTOR * ARROW_BASE_POINT - ARROW_HEAD_SIZE / 4 * ROOT_TWO) * 0.99, (BOARD_SCALING_FACTOR * ARROW_BASE_POINT + ARROW_HEAD_SIZE / 4 * ROOT_TWO) * 0.99);
				glVertex2f(-(BOARD_SCALING_FACTOR * ARROW_BASE_POINT + ARROW_HEAD_SIZE / 4 * ROOT_TWO) * 0.99, (BOARD_SCALING_FACTOR * ARROW_BASE_POINT + ARROW_HEAD_SIZE / 4 * ROOT_TWO) * 0.99);
			glEnd();

			drawCircleOutline(radius, centerX / BOARD_SCALING_FACTOR, centerY / BOARD_SCALING_FACTOR, CDA, -CDA / 2, CDA / 4 + ROUND_OFF_ERROR);

			glBegin(GL_TRIANGLES);
				glVertex2f(centerX - radius * BOARD_SCALING_FACTOR - ARROW_HEAD_SIZE / 2, centerY);
				glVertex2f(centerX - radius * BOARD_SCALING_FACTOR + ARROW_HEAD_SIZE / 2, centerY);
				glVertex2f(centerX - radius * BOARD_SCALING_FACTOR, centerY + ARROW_HEAD_SIZE / 2);
			glEnd();

			glBegin(GL_TRIANGLES);
				glVertex2f(centerX, centerY + radius * BOARD_SCALING_FACTOR + ARROW_HEAD_SIZE / 2);
				glVertex2f(centerX, centerY + radius * BOARD_SCALING_FACTOR - ARROW_HEAD_SIZE / 2);
				glVertex2f(centerX - ARROW_HEAD_SIZE / 2, centerY + radius * BOARD_SCALING_FACTOR);
			glEnd();
			break;

		case TOP_RIGHT:
			glBegin(GL_LINES);
				glVertex2f(BOARD_SCALING_FACTOR * ARROW_HEAD_POINT, BOARD_SCALING_FACTOR * ARROW_HEAD_POINT);
				glVertex2f(BOARD_SCALING_FACTOR * ARROW_BASE_POINT, BOARD_SCALING_FACTOR * ARROW_BASE_POINT);
			glEnd();

			glBegin(GL_TRIANGLES);
				glVertex2f((BOARD_SCALING_FACTOR * ARROW_BASE_POINT - ARROW_HEAD_SIZE / 4 * ROOT_TWO) * 0.99, (BOARD_SCALING_FACTOR * ARROW_BASE_POINT + ARROW_HEAD_SIZE / 4 * ROOT_TWO) * 0.99);
				glVertex2f((BOARD_SCALING_FACTOR * ARROW_BASE_POINT + ARROW_HEAD_SIZE / 4 * ROOT_TWO) * 0.99, (BOARD_SCALING_FACTOR * ARROW_BASE_POINT - ARROW_HEAD_SIZE / 4 * ROOT_TWO) * 0.99);
				glVertex2f((BOARD_SCALING_FACTOR * ARROW_BASE_POINT + ARROW_HEAD_SIZE / 4 * ROOT_TWO) * 0.99, (BOARD_SCALING_FACTOR * ARROW_BASE_POINT + ARROW_HEAD_SIZE / 4 * ROOT_TWO) * 0.99);
			glEnd();

			drawCircleOutline(radius, centerX / BOARD_SCALING_FACTOR, centerY / BOARD_SCALING_FACTOR, CDA, CDA / 4, CDA + ROUND_OFF_ERROR);

			glBegin(GL_TRIANGLES);
				glVertex2f(centerX + radius * BOARD_SCALING_FACTOR - ARROW_HEAD_SIZE / 2, centerY);
				glVertex2f(centerX + radius * BOARD_SCALING_FACTOR + ARROW_HEAD_SIZE / 2, centerY);
				glVertex2f(centerX + radius * BOARD_SCALING_FACTOR, centerY + ARROW_HEAD_SIZE / 2);
			glEnd();

			glBegin(GL_TRIANGLES);
				glVertex2f(centerX, centerY + radius * BOARD_SCALING_FACTOR + ARROW_HEAD_SIZE / 2);
				glVertex2f(centerX, centerY + radius * BOARD_SCALING_FACTOR - ARROW_HEAD_SIZE / 2);
				glVertex2f(centerX + ARROW_HEAD_SIZE / 2, centerY + radius * BOARD_SCALING_FACTOR);
			glEnd();
			break;

		case BOTTOM_LEFT:
			centerX *= -1; centerY *= -1;
			glBegin(GL_LINES);
				glVertex2f(-BOARD_SCALING_FACTOR * ARROW_HEAD_POINT, -BOARD_SCALING_FACTOR * ARROW_HEAD_POINT);
				glVertex2f(-BOARD_SCALING_FACTOR * ARROW_BASE_POINT, -BOARD_SCALING_FACTOR * ARROW_BASE_POINT);
			glEnd();

			glBegin(GL_TRIANGLES);
				glVertex2f(-(BOARD_SCALING_FACTOR * ARROW_BASE_POINT - ARROW_HEAD_SIZE / 4 * ROOT_TWO) * 0.99, -(BOARD_SCALING_FACTOR * ARROW_BASE_POINT + ARROW_HEAD_SIZE / 4 * ROOT_TWO) * 0.99);
				glVertex2f(-(BOARD_SCALING_FACTOR * ARROW_BASE_POINT + ARROW_HEAD_SIZE / 4 * ROOT_TWO) * 0.99, -(BOARD_SCALING_FACTOR * ARROW_BASE_POINT - ARROW_HEAD_SIZE / 4 * ROOT_TWO) * 0.99);
				glVertex2f(-(BOARD_SCALING_FACTOR * ARROW_BASE_POINT + ARROW_HEAD_SIZE / 4 * ROOT_TWO) * 0.99, -(BOARD_SCALING_FACTOR * ARROW_BASE_POINT + ARROW_HEAD_SIZE / 4 * ROOT_TWO) * 0.99);
			glEnd();

			drawCircleOutline(radius, centerX / BOARD_SCALING_FACTOR, centerY / BOARD_SCALING_FACTOR, CDA, -CDA / 4 - ROUND_OFF_ERROR, CDA / 2 + ROUND_OFF_ERROR);

			glBegin(GL_TRIANGLES);
				glVertex2f(centerX, centerY - radius * BOARD_SCALING_FACTOR - ARROW_HEAD_SIZE / 2);
				glVertex2f(centerX, centerY - radius * BOARD_SCALING_FACTOR + ARROW_HEAD_SIZE / 2);
				glVertex2f(centerX - ARROW_HEAD_SIZE / 2, centerY - radius * BOARD_SCALING_FACTOR);
			glEnd();

			glBegin(GL_TRIANGLES);
				glVertex2f(centerX - radius * BOARD_SCALING_FACTOR - ARROW_HEAD_SIZE / 2, centerY);
				glVertex2f(centerX - radius * BOARD_SCALING_FACTOR + ARROW_HEAD_SIZE / 2, centerY);
				glVertex2f(centerX - radius * BOARD_SCALING_FACTOR, centerY - ARROW_HEAD_SIZE / 2);
			glEnd();
			break;

		case BOTTOM_RIGHT:
			centerY *= -1;
			glBegin(GL_LINES);
				glVertex2f(BOARD_SCALING_FACTOR * ARROW_HEAD_POINT, -BOARD_SCALING_FACTOR * ARROW_HEAD_POINT);
				glVertex2f(BOARD_SCALING_FACTOR * ARROW_BASE_POINT, - BOARD_SCALING_FACTOR * ARROW_BASE_POINT);
			glEnd();

			glBegin(GL_TRIANGLES);
				glVertex2f((BOARD_SCALING_FACTOR * ARROW_BASE_POINT - ARROW_HEAD_SIZE / 4 * ROOT_TWO) * 0.99, -(BOARD_SCALING_FACTOR * ARROW_BASE_POINT + ARROW_HEAD_SIZE / 4 * ROOT_TWO) * 0.99);
				glVertex2f((BOARD_SCALING_FACTOR * ARROW_BASE_POINT + ARROW_HEAD_SIZE / 4 * ROOT_TWO) * 0.99, -(BOARD_SCALING_FACTOR * ARROW_BASE_POINT - ARROW_HEAD_SIZE / 4 * ROOT_TWO) * 0.99);
				glVertex2f((BOARD_SCALING_FACTOR * ARROW_BASE_POINT + ARROW_HEAD_SIZE / 4 * ROOT_TWO) * 0.99, -(BOARD_SCALING_FACTOR * ARROW_BASE_POINT + ARROW_HEAD_SIZE / 4 * ROOT_TWO) * 0.99);
			glEnd();

			drawCircleOutline(radius, centerX / BOARD_SCALING_FACTOR, centerY / BOARD_SCALING_FACTOR, CDA, -ROUND_OFF_ERROR, 3 * CDA / 4 + ROUND_OFF_ERROR);

			glBegin(GL_TRIANGLES);
				glVertex2f(centerX, centerY - radius * BOARD_SCALING_FACTOR - ARROW_HEAD_SIZE / 2);
				glVertex2f(centerX, centerY - radius * BOARD_SCALING_FACTOR + ARROW_HEAD_SIZE / 2);
				glVertex2f(centerX + ARROW_HEAD_SIZE / 2, centerY - radius * BOARD_SCALING_FACTOR);
			glEnd();

			glBegin(GL_TRIANGLES);
				glVertex2f(centerX + radius * BOARD_SCALING_FACTOR - ARROW_HEAD_SIZE / 2, centerY);
				glVertex2f(centerX + radius * BOARD_SCALING_FACTOR + ARROW_HEAD_SIZE / 2, centerY);
				glVertex2f(centerX + radius * BOARD_SCALING_FACTOR, centerY - ARROW_HEAD_SIZE / 2);
			glEnd();
			break;
	}
}
